// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.20.1
// source: credentials.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "tgvalidatord";

export interface Credentials {
  /**
   * Use username instead
   *
   * @deprecated
   */
  email: string;
  password: string;
  totp: string;
  username: string;
}

export interface SAMLAuthRequest {
  index: string;
  signedTrackedRequest: string;
  location: string;
}

export interface SAMLAuthRedirect {
  token: string;
  location: string;
}

export interface SAMLSession {
  token: string;
}

export interface OIDCLocation {
  location: string;
  state: string;
  nonce: string;
}

export interface OIDCSession {
  token: string;
}

function createBaseCredentials(): Credentials {
  return { email: "", password: "", totp: "", username: "" };
}

export const Credentials = {
  encode(message: Credentials, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.totp !== "") {
      writer.uint32(26).string(message.totp);
    }
    if (message.username !== "") {
      writer.uint32(34).string(message.username);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Credentials {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentials();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.totp = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.username = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Credentials {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      totp: isSet(object.totp) ? globalThis.String(object.totp) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: Credentials): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.totp !== "") {
      obj.totp = message.totp;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create(base?: DeepPartial<Credentials>): Credentials {
    return Credentials.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Credentials>): Credentials {
    const message = createBaseCredentials();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.totp = object.totp ?? "";
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseSAMLAuthRequest(): SAMLAuthRequest {
  return { index: "", signedTrackedRequest: "", location: "" };
}

export const SAMLAuthRequest = {
  encode(message: SAMLAuthRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== "") {
      writer.uint32(10).string(message.index);
    }
    if (message.signedTrackedRequest !== "") {
      writer.uint32(18).string(message.signedTrackedRequest);
    }
    if (message.location !== "") {
      writer.uint32(26).string(message.location);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SAMLAuthRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSAMLAuthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.index = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.signedTrackedRequest = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.location = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SAMLAuthRequest {
    return {
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      signedTrackedRequest: isSet(object.signedTrackedRequest) ? globalThis.String(object.signedTrackedRequest) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
    };
  },

  toJSON(message: SAMLAuthRequest): unknown {
    const obj: any = {};
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.signedTrackedRequest !== "") {
      obj.signedTrackedRequest = message.signedTrackedRequest;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    return obj;
  },

  create(base?: DeepPartial<SAMLAuthRequest>): SAMLAuthRequest {
    return SAMLAuthRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SAMLAuthRequest>): SAMLAuthRequest {
    const message = createBaseSAMLAuthRequest();
    message.index = object.index ?? "";
    message.signedTrackedRequest = object.signedTrackedRequest ?? "";
    message.location = object.location ?? "";
    return message;
  },
};

function createBaseSAMLAuthRedirect(): SAMLAuthRedirect {
  return { token: "", location: "" };
}

export const SAMLAuthRedirect = {
  encode(message: SAMLAuthRedirect, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.location !== "") {
      writer.uint32(18).string(message.location);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SAMLAuthRedirect {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSAMLAuthRedirect();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.location = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SAMLAuthRedirect {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
    };
  },

  toJSON(message: SAMLAuthRedirect): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    return obj;
  },

  create(base?: DeepPartial<SAMLAuthRedirect>): SAMLAuthRedirect {
    return SAMLAuthRedirect.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SAMLAuthRedirect>): SAMLAuthRedirect {
    const message = createBaseSAMLAuthRedirect();
    message.token = object.token ?? "";
    message.location = object.location ?? "";
    return message;
  },
};

function createBaseSAMLSession(): SAMLSession {
  return { token: "" };
}

export const SAMLSession = {
  encode(message: SAMLSession, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SAMLSession {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSAMLSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SAMLSession {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: SAMLSession): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<SAMLSession>): SAMLSession {
    return SAMLSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SAMLSession>): SAMLSession {
    const message = createBaseSAMLSession();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseOIDCLocation(): OIDCLocation {
  return { location: "", state: "", nonce: "" };
}

export const OIDCLocation = {
  encode(message: OIDCLocation, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.location !== "") {
      writer.uint32(10).string(message.location);
    }
    if (message.state !== "") {
      writer.uint32(18).string(message.state);
    }
    if (message.nonce !== "") {
      writer.uint32(26).string(message.nonce);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OIDCLocation {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOIDCLocation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.location = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.state = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.nonce = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OIDCLocation {
    return {
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      nonce: isSet(object.nonce) ? globalThis.String(object.nonce) : "",
    };
  },

  toJSON(message: OIDCLocation): unknown {
    const obj: any = {};
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.nonce !== "") {
      obj.nonce = message.nonce;
    }
    return obj;
  },

  create(base?: DeepPartial<OIDCLocation>): OIDCLocation {
    return OIDCLocation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OIDCLocation>): OIDCLocation {
    const message = createBaseOIDCLocation();
    message.location = object.location ?? "";
    message.state = object.state ?? "";
    message.nonce = object.nonce ?? "";
    return message;
  },
};

function createBaseOIDCSession(): OIDCSession {
  return { token: "" };
}

export const OIDCSession = {
  encode(message: OIDCSession, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OIDCSession {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOIDCSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OIDCSession {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: OIDCSession): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<OIDCSession>): OIDCSession {
    return OIDCSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OIDCSession>): OIDCSession {
    const message = createBaseOIDCSession();
    message.token = object.token ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
