// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: action.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action_Trigger_Kind int32

const (
	Action_Trigger_None    Action_Trigger_Kind = 0
	Action_Trigger_Balance Action_Trigger_Kind = 1
)

// Enum value maps for Action_Trigger_Kind.
var (
	Action_Trigger_Kind_name = map[int32]string{
		0: "None",
		1: "Balance",
	}
	Action_Trigger_Kind_value = map[string]int32{
		"None":    0,
		"Balance": 1,
	}
)

func (x Action_Trigger_Kind) Enum() *Action_Trigger_Kind {
	p := new(Action_Trigger_Kind)
	*p = x
	return p
}

func (x Action_Trigger_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Trigger_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[0].Descriptor()
}

func (Action_Trigger_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[0]
}

func (x Action_Trigger_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Trigger_Kind.Descriptor instead.
func (Action_Trigger_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 0, 0}
}

type Action_Source_Kind int32

const (
	Action_Source_None      Action_Source_Kind = 0
	Action_Source_AddressID Action_Source_Kind = 1
	Action_Source_WalletID  Action_Source_Kind = 2
)

// Enum value maps for Action_Source_Kind.
var (
	Action_Source_Kind_name = map[int32]string{
		0: "None",
		1: "AddressID",
		2: "WalletID",
	}
	Action_Source_Kind_value = map[string]int32{
		"None":      0,
		"AddressID": 1,
		"WalletID":  2,
	}
)

func (x Action_Source_Kind) Enum() *Action_Source_Kind {
	p := new(Action_Source_Kind)
	*p = x
	return p
}

func (x Action_Source_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Source_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[1].Descriptor()
}

func (Action_Source_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[1]
}

func (x Action_Source_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Source_Kind.Descriptor instead.
func (Action_Source_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 1, 0}
}

type Action_Destination_Kind int32

const (
	Action_Destination_None                 Action_Destination_Kind = 0
	Action_Destination_AddressID            Action_Destination_Kind = 1
	Action_Destination_WhitelistedAddressID Action_Destination_Kind = 2
	Action_Destination_WalletID             Action_Destination_Kind = 3
)

// Enum value maps for Action_Destination_Kind.
var (
	Action_Destination_Kind_name = map[int32]string{
		0: "None",
		1: "AddressID",
		2: "WhitelistedAddressID",
		3: "WalletID",
	}
	Action_Destination_Kind_value = map[string]int32{
		"None":                 0,
		"AddressID":            1,
		"WhitelistedAddressID": 2,
		"WalletID":             3,
	}
)

func (x Action_Destination_Kind) Enum() *Action_Destination_Kind {
	p := new(Action_Destination_Kind)
	*p = x
	return p
}

func (x Action_Destination_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Destination_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[2].Descriptor()
}

func (Action_Destination_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[2]
}

func (x Action_Destination_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Destination_Kind.Descriptor instead.
func (Action_Destination_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 2, 0}
}

type Action_Target_Kind int32

const (
	Action_Target_None    Action_Target_Kind = 0
	Action_Target_Address Action_Target_Kind = 1
	Action_Target_Wallet  Action_Target_Kind = 2
)

// Enum value maps for Action_Target_Kind.
var (
	Action_Target_Kind_name = map[int32]string{
		0: "None",
		1: "Address",
		2: "Wallet",
	}
	Action_Target_Kind_value = map[string]int32{
		"None":    0,
		"Address": 1,
		"Wallet":  2,
	}
)

func (x Action_Target_Kind) Enum() *Action_Target_Kind {
	p := new(Action_Target_Kind)
	*p = x
	return p
}

func (x Action_Target_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Target_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[3].Descriptor()
}

func (Action_Target_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[3]
}

func (x Action_Target_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Target_Kind.Descriptor instead.
func (Action_Target_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 3, 0}
}

type Action_Target_XAddress_Kind int32

const (
	Action_Target_XAddress__None     Action_Target_XAddress_Kind = 0
	Action_Target_XAddress_AddressID Action_Target_XAddress_Kind = 1
)

// Enum value maps for Action_Target_XAddress_Kind.
var (
	Action_Target_XAddress_Kind_name = map[int32]string{
		0: "_None",
		1: "AddressID",
	}
	Action_Target_XAddress_Kind_value = map[string]int32{
		"_None":     0,
		"AddressID": 1,
	}
)

func (x Action_Target_XAddress_Kind) Enum() *Action_Target_XAddress_Kind {
	p := new(Action_Target_XAddress_Kind)
	*p = x
	return p
}

func (x Action_Target_XAddress_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Target_XAddress_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[4].Descriptor()
}

func (Action_Target_XAddress_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[4]
}

func (x Action_Target_XAddress_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Target_XAddress_Kind.Descriptor instead.
func (Action_Target_XAddress_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 3, 0, 0}
}

type Action_Target_XWallet_Kind int32

const (
	Action_Target_XWallet___None   Action_Target_XWallet_Kind = 0
	Action_Target_XWallet_WalletID Action_Target_XWallet_Kind = 1
)

// Enum value maps for Action_Target_XWallet_Kind.
var (
	Action_Target_XWallet_Kind_name = map[int32]string{
		0: "__None",
		1: "WalletID",
	}
	Action_Target_XWallet_Kind_value = map[string]int32{
		"__None":   0,
		"WalletID": 1,
	}
)

func (x Action_Target_XWallet_Kind) Enum() *Action_Target_XWallet_Kind {
	p := new(Action_Target_XWallet_Kind)
	*p = x
	return p
}

func (x Action_Target_XWallet_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Target_XWallet_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[5].Descriptor()
}

func (Action_Target_XWallet_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[5]
}

func (x Action_Target_XWallet_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Target_XWallet_Kind.Descriptor instead.
func (Action_Target_XWallet_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 3, 1, 0}
}

type Action_Comparator_Kind int32

const (
	Action_Comparator_None        Action_Comparator_Kind = 0
	Action_Comparator_GreaterThan Action_Comparator_Kind = 1
	Action_Comparator_LowerThan   Action_Comparator_Kind = 2
)

// Enum value maps for Action_Comparator_Kind.
var (
	Action_Comparator_Kind_name = map[int32]string{
		0: "None",
		1: "GreaterThan",
		2: "LowerThan",
	}
	Action_Comparator_Kind_value = map[string]int32{
		"None":        0,
		"GreaterThan": 1,
		"LowerThan":   2,
	}
)

func (x Action_Comparator_Kind) Enum() *Action_Comparator_Kind {
	p := new(Action_Comparator_Kind)
	*p = x
	return p
}

func (x Action_Comparator_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Comparator_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[6].Descriptor()
}

func (Action_Comparator_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[6]
}

func (x Action_Comparator_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Comparator_Kind.Descriptor instead.
func (Action_Comparator_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 4, 0}
}

type Action_Amount_Kind int32

const (
	Action_Amount_None         Action_Amount_Kind = 0
	Action_Amount_CryptoAmount Action_Amount_Kind = 1
)

// Enum value maps for Action_Amount_Kind.
var (
	Action_Amount_Kind_name = map[int32]string{
		0: "None",
		1: "CryptoAmount",
	}
	Action_Amount_Kind_value = map[string]int32{
		"None":         0,
		"CryptoAmount": 1,
	}
)

func (x Action_Amount_Kind) Enum() *Action_Amount_Kind {
	p := new(Action_Amount_Kind)
	*p = x
	return p
}

func (x Action_Amount_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Amount_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[7].Descriptor()
}

func (Action_Amount_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[7]
}

func (x Action_Amount_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Amount_Kind.Descriptor instead.
func (Action_Amount_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 5, 0}
}

type Action_Task_Kind int32

const (
	Action_Task_None         Action_Task_Kind = 0
	Action_Task_Transfer     Action_Task_Kind = 1
	Action_Task_Notification Action_Task_Kind = 2
)

// Enum value maps for Action_Task_Kind.
var (
	Action_Task_Kind_name = map[int32]string{
		0: "None",
		1: "Transfer",
		2: "Notification",
	}
	Action_Task_Kind_value = map[string]int32{
		"None":         0,
		"Transfer":     1,
		"Notification": 2,
	}
)

func (x Action_Task_Kind) Enum() *Action_Task_Kind {
	p := new(Action_Task_Kind)
	*p = x
	return p
}

func (x Action_Task_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Task_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[8].Descriptor()
}

func (Action_Task_Kind) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[8]
}

func (x Action_Task_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Task_Kind.Descriptor instead.
func (Action_Task_Kind) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 6, 0}
}

type ActionEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        uint64                  `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Label           string                  `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Action          *Action                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Status          string                  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreationDate    *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	UpdateDate      *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=updateDate,proto3" json:"updateDate,omitempty"`
	Lastcheckeddate *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=lastcheckeddate,proto3" json:"lastcheckeddate,omitempty"`
	AutoApprove     bool                    `protobuf:"varint,9,opt,name=autoApprove,proto3" json:"autoApprove,omitempty"`
	Attributes      []*ActionAttribute      `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Trails          []*ActionEnvelope_Trail `protobuf:"bytes,11,rep,name=trails,proto3" json:"trails,omitempty"`
}

func (x *ActionEnvelope) Reset() {
	*x = ActionEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEnvelope) ProtoMessage() {}

func (x *ActionEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEnvelope.ProtoReflect.Descriptor instead.
func (*ActionEnvelope) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionEnvelope) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActionEnvelope) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ActionEnvelope) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ActionEnvelope) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionEnvelope) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionEnvelope) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *ActionEnvelope) GetUpdateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateDate
	}
	return nil
}

func (x *ActionEnvelope) GetLastcheckeddate() *timestamppb.Timestamp {
	if x != nil {
		return x.Lastcheckeddate
	}
	return nil
}

func (x *ActionEnvelope) GetAutoApprove() bool {
	if x != nil {
		return x.AutoApprove
	}
	return false
}

func (x *ActionEnvelope) GetAttributes() []*ActionAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ActionEnvelope) GetTrails() []*ActionEnvelope_Trail {
	if x != nil {
		return x.Trails
	}
	return nil
}

// when <trigger> then perform <actions>
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trigger *Action_Trigger `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Tasks   []*Action_Task  `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetTrigger() *Action_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *Action) GetTasks() []*Action_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ActionAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId    uint64 `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Key         string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value       string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ContentType string `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
}

func (x *ActionAttribute) Reset() {
	*x = ActionAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionAttribute) ProtoMessage() {}

func (x *ActionAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionAttribute.ProtoReflect.Descriptor instead.
func (*ActionAttribute) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{2}
}

func (x *ActionAttribute) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActionAttribute) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ActionAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ActionAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ActionAttribute) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ActionEnvelope_Trail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action       string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Comment      string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Date         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	ActionStatus string                 `protobuf:"bytes,5,opt,name=actionStatus,proto3" json:"actionStatus,omitempty"`
}

func (x *ActionEnvelope_Trail) Reset() {
	*x = ActionEnvelope_Trail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionEnvelope_Trail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEnvelope_Trail) ProtoMessage() {}

func (x *ActionEnvelope_Trail) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEnvelope_Trail.ProtoReflect.Descriptor instead.
func (*ActionEnvelope_Trail) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ActionEnvelope_Trail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActionEnvelope_Trail) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionEnvelope_Trail) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ActionEnvelope_Trail) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ActionEnvelope_Trail) GetActionStatus() string {
	if x != nil {
		return x.ActionStatus
	}
	return ""
}

type Action_Trigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string                   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Balance *Action_Trigger_XBalance `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Action_Trigger) Reset() {
	*x = Action_Trigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Trigger) ProtoMessage() {}

func (x *Action_Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Trigger.ProtoReflect.Descriptor instead.
func (*Action_Trigger) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Action_Trigger) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Trigger) GetBalance() *Action_Trigger_XBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type Action_Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	AddressID uint64 `protobuf:"varint,2,opt,name=addressID,proto3" json:"addressID,omitempty"`
	WalletID  uint64 `protobuf:"varint,3,opt,name=walletID,proto3" json:"walletID,omitempty"`
}

func (x *Action_Source) Reset() {
	*x = Action_Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Source) ProtoMessage() {}

func (x *Action_Source) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Source.ProtoReflect.Descriptor instead.
func (*Action_Source) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Action_Source) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Source) GetAddressID() uint64 {
	if x != nil {
		return x.AddressID
	}
	return 0
}

func (x *Action_Source) GetWalletID() uint64 {
	if x != nil {
		return x.WalletID
	}
	return 0
}

type Action_Destination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind                 string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	AddressID            uint64 `protobuf:"varint,2,opt,name=addressID,proto3" json:"addressID,omitempty"`
	WhitelistedAddressID uint64 `protobuf:"varint,3,opt,name=whitelistedAddressID,proto3" json:"whitelistedAddressID,omitempty"`
	WalletID             uint64 `protobuf:"varint,4,opt,name=walletID,proto3" json:"walletID,omitempty"`
}

func (x *Action_Destination) Reset() {
	*x = Action_Destination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Destination) ProtoMessage() {}

func (x *Action_Destination) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Destination.ProtoReflect.Descriptor instead.
func (*Action_Destination) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Action_Destination) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Destination) GetAddressID() uint64 {
	if x != nil {
		return x.AddressID
	}
	return 0
}

func (x *Action_Destination) GetWhitelistedAddressID() uint64 {
	if x != nil {
		return x.WhitelistedAddressID
	}
	return 0
}

func (x *Action_Destination) GetWalletID() uint64 {
	if x != nil {
		return x.WalletID
	}
	return 0
}

type Action_Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string                  `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Address *Action_Target_XAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Wallet  *Action_Target_XWallet  `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
}

func (x *Action_Target) Reset() {
	*x = Action_Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Target) ProtoMessage() {}

func (x *Action_Target) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Target.ProtoReflect.Descriptor instead.
func (*Action_Target) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Action_Target) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Target) GetAddress() *Action_Target_XAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Action_Target) GetWallet() *Action_Target_XWallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type Action_Comparator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *Action_Comparator) Reset() {
	*x = Action_Comparator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Comparator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Comparator) ProtoMessage() {}

func (x *Action_Comparator) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Comparator.ProtoReflect.Descriptor instead.
func (*Action_Comparator) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 4}
}

func (x *Action_Comparator) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Action_Amount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind         string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	CryptoAmount string `protobuf:"bytes,2,opt,name=cryptoAmount,proto3" json:"cryptoAmount,omitempty"`
}

func (x *Action_Amount) Reset() {
	*x = Action_Amount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Amount) ProtoMessage() {}

func (x *Action_Amount) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Amount.ProtoReflect.Descriptor instead.
func (*Action_Amount) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 5}
}

func (x *Action_Amount) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Amount) GetCryptoAmount() string {
	if x != nil {
		return x.CryptoAmount
	}
	return ""
}

type Action_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind         string                     `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Transfer     *Action_Task_XTransfer     `protobuf:"bytes,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Notification *Action_Task_XNotification `protobuf:"bytes,3,opt,name=notification,proto3" json:"notification,omitempty"`
}

func (x *Action_Task) Reset() {
	*x = Action_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Task) ProtoMessage() {}

func (x *Action_Task) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Task.ProtoReflect.Descriptor instead.
func (*Action_Task) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 6}
}

func (x *Action_Task) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Task) GetTransfer() *Action_Task_XTransfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *Action_Task) GetNotification() *Action_Task_XNotification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type Action_Trigger_XBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target     *Action_Target     `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Comparator *Action_Comparator `protobuf:"bytes,2,opt,name=comparator,proto3" json:"comparator,omitempty"`
	Amount     *Action_Amount     `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Action_Trigger_XBalance) Reset() {
	*x = Action_Trigger_XBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Trigger_XBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Trigger_XBalance) ProtoMessage() {}

func (x *Action_Trigger_XBalance) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Trigger_XBalance.ProtoReflect.Descriptor instead.
func (*Action_Trigger_XBalance) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Action_Trigger_XBalance) GetTarget() *Action_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Action_Trigger_XBalance) GetComparator() *Action_Comparator {
	if x != nil {
		return x.Comparator
	}
	return nil
}

func (x *Action_Trigger_XBalance) GetAmount() *Action_Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

type Action_Target_XAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	AddressID uint64 `protobuf:"varint,2,opt,name=addressID,proto3" json:"addressID,omitempty"`
}

func (x *Action_Target_XAddress) Reset() {
	*x = Action_Target_XAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Target_XAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Target_XAddress) ProtoMessage() {}

func (x *Action_Target_XAddress) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Target_XAddress.ProtoReflect.Descriptor instead.
func (*Action_Target_XAddress) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *Action_Target_XAddress) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Target_XAddress) GetAddressID() uint64 {
	if x != nil {
		return x.AddressID
	}
	return 0
}

type Action_Target_XWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	WalletID uint64 `protobuf:"varint,2,opt,name=walletID,proto3" json:"walletID,omitempty"`
}

func (x *Action_Target_XWallet) Reset() {
	*x = Action_Target_XWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Target_XWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Target_XWallet) ProtoMessage() {}

func (x *Action_Target_XWallet) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Target_XWallet.ProtoReflect.Descriptor instead.
func (*Action_Target_XWallet) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 3, 1}
}

func (x *Action_Target_XWallet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action_Target_XWallet) GetWalletID() uint64 {
	if x != nil {
		return x.WalletID
	}
	return 0
}

type Action_Task_XTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From        *Action_Source      `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To          *Action_Destination `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount      *Action_Amount      `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TopUp       bool                `protobuf:"varint,4,opt,name=topUp,proto3" json:"topUp,omitempty"`
	UseAllFunds bool                `protobuf:"varint,5,opt,name=useAllFunds,proto3" json:"useAllFunds,omitempty"`
}

func (x *Action_Task_XTransfer) Reset() {
	*x = Action_Task_XTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Task_XTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Task_XTransfer) ProtoMessage() {}

func (x *Action_Task_XTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Task_XTransfer.ProtoReflect.Descriptor instead.
func (*Action_Task_XTransfer) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 6, 0}
}

func (x *Action_Task_XTransfer) GetFrom() *Action_Source {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Action_Task_XTransfer) GetTo() *Action_Destination {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Action_Task_XTransfer) GetAmount() *Action_Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Action_Task_XTransfer) GetTopUp() bool {
	if x != nil {
		return x.TopUp
	}
	return false
}

func (x *Action_Task_XTransfer) GetUseAllFunds() bool {
	if x != nil {
		return x.UseAllFunds
	}
	return false
}

type Action_Task_XNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailAddresses      []string `protobuf:"bytes,1,rep,name=emailAddresses,proto3" json:"emailAddresses,omitempty"`
	NotificationMessage string   `protobuf:"bytes,2,opt,name=notificationMessage,proto3" json:"notificationMessage,omitempty"`
	NumberOfReminders   uint64   `protobuf:"varint,3,opt,name=numberOfReminders,proto3" json:"numberOfReminders,omitempty"`
}

func (x *Action_Task_XNotification) Reset() {
	*x = Action_Task_XNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Task_XNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Task_XNotification) ProtoMessage() {}

func (x *Action_Task_XNotification) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Task_XNotification.ProtoReflect.Descriptor instead.
func (*Action_Task_XNotification) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1, 6, 1}
}

func (x *Action_Task_XNotification) GetEmailAddresses() []string {
	if x != nil {
		return x.EmailAddresses
	}
	return nil
}

func (x *Action_Task_XNotification) GetNotificationMessage() string {
	if x != nil {
		return x.NotificationMessage
	}
	return ""
}

func (x *Action_Task_XNotification) GetNumberOfReminders() uint64 {
	if x != nil {
		return x.NumberOfReminders
	}
	return 0
}

var File_action_proto protoreflect.FileDescriptor

var file_action_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x05,
	0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x65, 0x64, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x6f, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x61, 0x75, 0x74, 0x6f, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x3d, 0x0a, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x74,
	0x72, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x67,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x52,
	0x06, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x9d, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x9f, 0x0f, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x52, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x05, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x67, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x1a, 0xb5, 0x02, 0x0a, 0x07,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74,
	0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x5f, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0xb5, 0x01, 0x0a,
	0x08, 0x5f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x67, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x3f,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x33, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1d, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x10, 0x01, 0x1a, 0x85, 0x01, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x22, 0x2d, 0x0a, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x10, 0x02, 0x1a, 0xd8, 0x01, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x12, 0x32, 0x0a,
	0x14, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x77, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x22, 0x47, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x10, 0x01, 0x12, 0x18,
	0x0a, 0x14, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x49, 0x44, 0x10, 0x03, 0x1a, 0x81, 0x03, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x2e, 0x5f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x2e, 0x5f, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x06, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x1a, 0x5e, 0x0a, 0x08, 0x5f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44,
	0x22, 0x20, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x5f, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44,
	0x10, 0x01, 0x1a, 0x5b, 0x0a, 0x07, 0x5f, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x22, 0x20, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0a, 0x0a, 0x06, 0x5f, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x10, 0x01, 0x22,
	0x29, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x10, 0x02, 0x1a, 0x52, 0x0a, 0x0a, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x30, 0x0a, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x47, 0x72, 0x65, 0x61, 0x74, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x10, 0x02, 0x1a, 0x64,
	0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x22, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x10, 0x01, 0x1a, 0xd2, 0x04, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x3f, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x5f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x2e, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0xdb, 0x01, 0x0a, 0x09, 0x5f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x2f, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x67,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x30,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x67, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x33, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x55, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x55, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x75,
	0x73, 0x65, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x1a, 0x97, 0x01,
	0x0a, 0x0d, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x26, 0x0a, 0x0e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x23, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x75, 0x72, 0x75,
	0x73, 0x68, 0x71, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_action_proto_rawDescOnce sync.Once
	file_action_proto_rawDescData = file_action_proto_rawDesc
)

func file_action_proto_rawDescGZIP() []byte {
	file_action_proto_rawDescOnce.Do(func() {
		file_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_action_proto_rawDescData)
	})
	return file_action_proto_rawDescData
}

var file_action_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_action_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_action_proto_goTypes = []interface{}{
	(Action_Trigger_Kind)(0),          // 0: tgvalidatord.Action.Trigger.Kind
	(Action_Source_Kind)(0),           // 1: tgvalidatord.Action.Source.Kind
	(Action_Destination_Kind)(0),      // 2: tgvalidatord.Action.Destination.Kind
	(Action_Target_Kind)(0),           // 3: tgvalidatord.Action.Target.Kind
	(Action_Target_XAddress_Kind)(0),  // 4: tgvalidatord.Action.Target._Address.Kind
	(Action_Target_XWallet_Kind)(0),   // 5: tgvalidatord.Action.Target._Wallet.Kind
	(Action_Comparator_Kind)(0),       // 6: tgvalidatord.Action.Comparator.Kind
	(Action_Amount_Kind)(0),           // 7: tgvalidatord.Action.Amount.Kind
	(Action_Task_Kind)(0),             // 8: tgvalidatord.Action.Task.Kind
	(*ActionEnvelope)(nil),            // 9: tgvalidatord.ActionEnvelope
	(*Action)(nil),                    // 10: tgvalidatord.Action
	(*ActionAttribute)(nil),           // 11: tgvalidatord.ActionAttribute
	(*ActionEnvelope_Trail)(nil),      // 12: tgvalidatord.ActionEnvelope.Trail
	(*Action_Trigger)(nil),            // 13: tgvalidatord.Action.Trigger
	(*Action_Source)(nil),             // 14: tgvalidatord.Action.Source
	(*Action_Destination)(nil),        // 15: tgvalidatord.Action.Destination
	(*Action_Target)(nil),             // 16: tgvalidatord.Action.Target
	(*Action_Comparator)(nil),         // 17: tgvalidatord.Action.Comparator
	(*Action_Amount)(nil),             // 18: tgvalidatord.Action.Amount
	(*Action_Task)(nil),               // 19: tgvalidatord.Action.Task
	(*Action_Trigger_XBalance)(nil),   // 20: tgvalidatord.Action.Trigger._Balance
	(*Action_Target_XAddress)(nil),    // 21: tgvalidatord.Action.Target._Address
	(*Action_Target_XWallet)(nil),     // 22: tgvalidatord.Action.Target._Wallet
	(*Action_Task_XTransfer)(nil),     // 23: tgvalidatord.Action.Task._Transfer
	(*Action_Task_XNotification)(nil), // 24: tgvalidatord.Action.Task._Notification
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
}
var file_action_proto_depIdxs = []int32{
	10, // 0: tgvalidatord.ActionEnvelope.action:type_name -> tgvalidatord.Action
	25, // 1: tgvalidatord.ActionEnvelope.creationDate:type_name -> google.protobuf.Timestamp
	25, // 2: tgvalidatord.ActionEnvelope.updateDate:type_name -> google.protobuf.Timestamp
	25, // 3: tgvalidatord.ActionEnvelope.lastcheckeddate:type_name -> google.protobuf.Timestamp
	11, // 4: tgvalidatord.ActionEnvelope.attributes:type_name -> tgvalidatord.ActionAttribute
	12, // 5: tgvalidatord.ActionEnvelope.trails:type_name -> tgvalidatord.ActionEnvelope.Trail
	13, // 6: tgvalidatord.Action.trigger:type_name -> tgvalidatord.Action.Trigger
	19, // 7: tgvalidatord.Action.tasks:type_name -> tgvalidatord.Action.Task
	25, // 8: tgvalidatord.ActionEnvelope.Trail.date:type_name -> google.protobuf.Timestamp
	20, // 9: tgvalidatord.Action.Trigger.balance:type_name -> tgvalidatord.Action.Trigger._Balance
	21, // 10: tgvalidatord.Action.Target.address:type_name -> tgvalidatord.Action.Target._Address
	22, // 11: tgvalidatord.Action.Target.wallet:type_name -> tgvalidatord.Action.Target._Wallet
	23, // 12: tgvalidatord.Action.Task.transfer:type_name -> tgvalidatord.Action.Task._Transfer
	24, // 13: tgvalidatord.Action.Task.notification:type_name -> tgvalidatord.Action.Task._Notification
	16, // 14: tgvalidatord.Action.Trigger._Balance.target:type_name -> tgvalidatord.Action.Target
	17, // 15: tgvalidatord.Action.Trigger._Balance.comparator:type_name -> tgvalidatord.Action.Comparator
	18, // 16: tgvalidatord.Action.Trigger._Balance.amount:type_name -> tgvalidatord.Action.Amount
	14, // 17: tgvalidatord.Action.Task._Transfer.from:type_name -> tgvalidatord.Action.Source
	15, // 18: tgvalidatord.Action.Task._Transfer.to:type_name -> tgvalidatord.Action.Destination
	18, // 19: tgvalidatord.Action.Task._Transfer.amount:type_name -> tgvalidatord.Action.Amount
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_action_proto_init() }
func file_action_proto_init() {
	if File_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionEnvelope_Trail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Trigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Destination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Comparator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Amount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Trigger_XBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Target_XAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Target_XWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Task_XTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Task_XNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_action_proto_rawDesc,
			NumEnums:      9,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_proto_goTypes,
		DependencyIndexes: file_action_proto_depIdxs,
		EnumInfos:         file_action_proto_enumTypes,
		MessageInfos:      file_action_proto_msgTypes,
	}.Build()
	File_action_proto = out.File
	file_action_proto_rawDesc = nil
	file_action_proto_goTypes = nil
	file_action_proto_depIdxs = nil
}
