// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: approvers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApproversGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalGroupID   string `protobuf:"bytes,1,opt,name=externalGroupID,proto3" json:"externalGroupID,omitempty"`
	MinimumSignatures uint32 `protobuf:"varint,2,opt,name=minimumSignatures,proto3" json:"minimumSignatures,omitempty"`
}

func (x *ApproversGroup) Reset() {
	*x = ApproversGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_approvers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproversGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproversGroup) ProtoMessage() {}

func (x *ApproversGroup) ProtoReflect() protoreflect.Message {
	mi := &file_approvers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproversGroup.ProtoReflect.Descriptor instead.
func (*ApproversGroup) Descriptor() ([]byte, []int) {
	return file_approvers_proto_rawDescGZIP(), []int{0}
}

func (x *ApproversGroup) GetExternalGroupID() string {
	if x != nil {
		return x.ExternalGroupID
	}
	return ""
}

func (x *ApproversGroup) GetMinimumSignatures() uint32 {
	if x != nil {
		return x.MinimumSignatures
	}
	return 0
}

type ParallelApproversGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequential []*ApproversGroup `protobuf:"bytes,1,rep,name=sequential,proto3" json:"sequential,omitempty"`
}

func (x *ParallelApproversGroups) Reset() {
	*x = ParallelApproversGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_approvers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParallelApproversGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParallelApproversGroups) ProtoMessage() {}

func (x *ParallelApproversGroups) ProtoReflect() protoreflect.Message {
	mi := &file_approvers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParallelApproversGroups.ProtoReflect.Descriptor instead.
func (*ParallelApproversGroups) Descriptor() ([]byte, []int) {
	return file_approvers_proto_rawDescGZIP(), []int{1}
}

func (x *ParallelApproversGroups) GetSequential() []*ApproversGroup {
	if x != nil {
		return x.Sequential
	}
	return nil
}

type Approvers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parallel []*ParallelApproversGroups `protobuf:"bytes,1,rep,name=parallel,proto3" json:"parallel,omitempty"`
}

func (x *Approvers) Reset() {
	*x = Approvers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_approvers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approvers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approvers) ProtoMessage() {}

func (x *Approvers) ProtoReflect() protoreflect.Message {
	mi := &file_approvers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approvers.ProtoReflect.Descriptor instead.
func (*Approvers) Descriptor() ([]byte, []int) {
	return file_approvers_proto_rawDescGZIP(), []int{2}
}

func (x *Approvers) GetParallel() []*ParallelApproversGroups {
	if x != nil {
		return x.Parallel
	}
	return nil
}

var File_approvers_proto protoreflect.FileDescriptor

var file_approvers_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x22,
	0x68, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x6d,
	0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x57, 0x0a, 0x17, 0x50, 0x61, 0x72,
	0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72,
	0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x22, 0x4e, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x12,
	0x41, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64,
	0x2e, 0x50, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x72, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x08, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c,
	0x65, 0x6c, 0x42, 0x23, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x75, 0x72, 0x75, 0x73,
	0x68, 0x71, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_approvers_proto_rawDescOnce sync.Once
	file_approvers_proto_rawDescData = file_approvers_proto_rawDesc
)

func file_approvers_proto_rawDescGZIP() []byte {
	file_approvers_proto_rawDescOnce.Do(func() {
		file_approvers_proto_rawDescData = protoimpl.X.CompressGZIP(file_approvers_proto_rawDescData)
	})
	return file_approvers_proto_rawDescData
}

var file_approvers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_approvers_proto_goTypes = []interface{}{
	(*ApproversGroup)(nil),          // 0: tgvalidatord.ApproversGroup
	(*ParallelApproversGroups)(nil), // 1: tgvalidatord.ParallelApproversGroups
	(*Approvers)(nil),               // 2: tgvalidatord.Approvers
}
var file_approvers_proto_depIdxs = []int32{
	0, // 0: tgvalidatord.ParallelApproversGroups.sequential:type_name -> tgvalidatord.ApproversGroup
	1, // 1: tgvalidatord.Approvers.parallel:type_name -> tgvalidatord.ParallelApproversGroups
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_approvers_proto_init() }
func file_approvers_proto_init() {
	if File_approvers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_approvers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproversGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_approvers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParallelApproversGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_approvers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Approvers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_approvers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_approvers_proto_goTypes,
		DependencyIndexes: file_approvers_proto_depIdxs,
		MessageInfos:      file_approvers_proto_msgTypes,
	}.Build()
	File_approvers_proto = out.File
	file_approvers_proto_rawDesc = nil
	file_approvers_proto_goTypes = nil
	file_approvers_proto_depIdxs = nil
}
