// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: credentials.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Marked as deprecated in credentials.proto.
	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // Use username instead
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Totp     string `protobuf:"bytes,3,opt,name=totp,proto3" json:"totp,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in credentials.proto.
func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Credentials) GetTotp() string {
	if x != nil {
		return x.Totp
	}
	return ""
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SAMLAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index                string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	SignedTrackedRequest string `protobuf:"bytes,2,opt,name=signedTrackedRequest,proto3" json:"signedTrackedRequest,omitempty"`
	Location             string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *SAMLAuthRequest) Reset() {
	*x = SAMLAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAMLAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAMLAuthRequest) ProtoMessage() {}

func (x *SAMLAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAMLAuthRequest.ProtoReflect.Descriptor instead.
func (*SAMLAuthRequest) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *SAMLAuthRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *SAMLAuthRequest) GetSignedTrackedRequest() string {
	if x != nil {
		return x.SignedTrackedRequest
	}
	return ""
}

func (x *SAMLAuthRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type SAMLAuthRedirect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *SAMLAuthRedirect) Reset() {
	*x = SAMLAuthRedirect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAMLAuthRedirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAMLAuthRedirect) ProtoMessage() {}

func (x *SAMLAuthRedirect) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAMLAuthRedirect.ProtoReflect.Descriptor instead.
func (*SAMLAuthRedirect) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *SAMLAuthRedirect) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SAMLAuthRedirect) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type SAMLSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SAMLSession) Reset() {
	*x = SAMLSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAMLSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAMLSession) ProtoMessage() {}

func (x *SAMLSession) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAMLSession.ProtoReflect.Descriptor instead.
func (*SAMLSession) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{3}
}

func (x *SAMLSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OIDCLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	State    string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Nonce    string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *OIDCLocation) Reset() {
	*x = OIDCLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OIDCLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCLocation) ProtoMessage() {}

func (x *OIDCLocation) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCLocation.ProtoReflect.Descriptor instead.
func (*OIDCLocation) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{4}
}

func (x *OIDCLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *OIDCLocation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OIDCLocation) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type OIDCSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *OIDCSession) Reset() {
	*x = OIDCSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OIDCSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCSession) ProtoMessage() {}

func (x *OIDCSession) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCSession.ProtoReflect.Descriptor instead.
func (*OIDCSession) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{5}
}

func (x *OIDCSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_credentials_proto protoreflect.FileDescriptor

var file_credentials_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x64, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xae, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x12, 0x18, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x02, 0x18, 0x01, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x3b, 0x0a, 0x04, 0x74, 0x6f, 0x74, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x27, 0x92, 0x41, 0x24, 0x32, 0x22, 0x54, 0x69, 0x6d, 0x65,
	0x2d, 0x62, 0x61, 0x73, 0x65, 0x64, 0x20, 0x4f, 0x6e, 0x65, 0x20, 0x54, 0x69, 0x6d, 0x65, 0x20,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x20, 0x28, 0x32, 0x46, 0x41, 0x29, 0x52, 0x04,
	0x74, 0x6f, 0x74, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x3a, 0x10, 0x92, 0x41, 0x0d, 0x0a, 0x0b, 0xd2, 0x01, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x77, 0x0a, 0x0f, 0x53, 0x41, 0x4d, 0x4c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x32, 0x0a, 0x14, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x10, 0x53,
	0x41, 0x4d, 0x4c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x41, 0x4d, 0x4c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x56, 0x0a, 0x0c, 0x4f, 0x49, 0x44, 0x43, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x23,
	0x0a, 0x0b, 0x4f, 0x49, 0x44, 0x43, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x42, 0x23, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x75, 0x72, 0x75,
	0x73, 0x68, 0x71, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_credentials_proto_rawDescOnce sync.Once
	file_credentials_proto_rawDescData = file_credentials_proto_rawDesc
)

func file_credentials_proto_rawDescGZIP() []byte {
	file_credentials_proto_rawDescOnce.Do(func() {
		file_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(file_credentials_proto_rawDescData)
	})
	return file_credentials_proto_rawDescData
}

var file_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_credentials_proto_goTypes = []interface{}{
	(*Credentials)(nil),      // 0: tgvalidatord.Credentials
	(*SAMLAuthRequest)(nil),  // 1: tgvalidatord.SAMLAuthRequest
	(*SAMLAuthRedirect)(nil), // 2: tgvalidatord.SAMLAuthRedirect
	(*SAMLSession)(nil),      // 3: tgvalidatord.SAMLSession
	(*OIDCLocation)(nil),     // 4: tgvalidatord.OIDCLocation
	(*OIDCSession)(nil),      // 5: tgvalidatord.OIDCSession
}
var file_credentials_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_credentials_proto_init() }
func file_credentials_proto_init() {
	if File_credentials_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_credentials_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAMLAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAMLAuthRedirect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAMLSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OIDCLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OIDCSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_credentials_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credentials_proto_goTypes,
		DependencyIndexes: file_credentials_proto_depIdxs,
		MessageInfos:      file_credentials_proto_msgTypes,
	}.Build()
	File_credentials_proto = out.File
	file_credentials_proto_rawDesc = nil
	file_credentials_proto_goTypes = nil
	file_credentials_proto_depIdxs = nil
}
