// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: token-metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERCTokenMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Decimals    uint64 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	DataType    string `protobuf:"bytes,4,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Base64Data  string `protobuf:"bytes,5,opt,name=base64Data,proto3" json:"base64Data,omitempty"`
	Uri         string `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *ERCTokenMetadata) Reset() {
	*x = ERCTokenMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ERCTokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ERCTokenMetadata) ProtoMessage() {}

func (x *ERCTokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_token_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ERCTokenMetadata.ProtoReflect.Descriptor instead.
func (*ERCTokenMetadata) Descriptor() ([]byte, []int) {
	return file_token_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ERCTokenMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ERCTokenMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ERCTokenMetadata) GetDecimals() uint64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *ERCTokenMetadata) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ERCTokenMetadata) GetBase64Data() string {
	if x != nil {
		return x.Base64Data
	}
	return ""
}

func (x *ERCTokenMetadata) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type FATokenMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol     string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals   uint64 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	DataType   string `protobuf:"bytes,4,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Base64Data string `protobuf:"bytes,5,opt,name=base64Data,proto3" json:"base64Data,omitempty"`
	Uri        string `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *FATokenMetadata) Reset() {
	*x = FATokenMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FATokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FATokenMetadata) ProtoMessage() {}

func (x *FATokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_token_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FATokenMetadata.ProtoReflect.Descriptor instead.
func (*FATokenMetadata) Descriptor() ([]byte, []int) {
	return file_token_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *FATokenMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FATokenMetadata) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FATokenMetadata) GetDecimals() uint64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *FATokenMetadata) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *FATokenMetadata) GetBase64Data() string {
	if x != nil {
		return x.Base64Data
	}
	return ""
}

func (x *FATokenMetadata) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type CryptoPunkMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PunkId         uint64 `protobuf:"varint,1,opt,name=punkId,proto3" json:"punkId,omitempty"`
	PunkAttributes string `protobuf:"bytes,2,opt,name=punkAttributes,proto3" json:"punkAttributes,omitempty"`
	Image          []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *CryptoPunkMetadata) Reset() {
	*x = CryptoPunkMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_metadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoPunkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoPunkMetadata) ProtoMessage() {}

func (x *CryptoPunkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_token_metadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoPunkMetadata.ProtoReflect.Descriptor instead.
func (*CryptoPunkMetadata) Descriptor() ([]byte, []int) {
	return file_token_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *CryptoPunkMetadata) GetPunkId() uint64 {
	if x != nil {
		return x.PunkId
	}
	return 0
}

func (x *CryptoPunkMetadata) GetPunkAttributes() string {
	if x != nil {
		return x.PunkAttributes
	}
	return ""
}

func (x *CryptoPunkMetadata) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_token_metadata_proto protoreflect.FileDescriptor

var file_token_metadata_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x10, 0x45, 0x52, 0x43, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x36,
	0x34, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x36, 0x34, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0xa7, 0x01, 0x0a, 0x0f, 0x46, 0x41,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x22, 0x6a, 0x0a, 0x12, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x50, 0x75, 0x6e,
	0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x6e,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x75, 0x6e, 0x6b, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x75, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x75, 0x6e, 0x6b, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42,
	0x23, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x75, 0x72, 0x75, 0x73, 0x68, 0x71, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token_metadata_proto_rawDescOnce sync.Once
	file_token_metadata_proto_rawDescData = file_token_metadata_proto_rawDesc
)

func file_token_metadata_proto_rawDescGZIP() []byte {
	file_token_metadata_proto_rawDescOnce.Do(func() {
		file_token_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_metadata_proto_rawDescData)
	})
	return file_token_metadata_proto_rawDescData
}

var file_token_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_token_metadata_proto_goTypes = []interface{}{
	(*ERCTokenMetadata)(nil),   // 0: tgvalidatord.ERCTokenMetadata
	(*FATokenMetadata)(nil),    // 1: tgvalidatord.FATokenMetadata
	(*CryptoPunkMetadata)(nil), // 2: tgvalidatord.CryptoPunkMetadata
}
var file_token_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_metadata_proto_init() }
func file_token_metadata_proto_init() {
	if File_token_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ERCTokenMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FATokenMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_metadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoPunkMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_metadata_proto_goTypes,
		DependencyIndexes: file_token_metadata_proto_depIdxs,
		MessageInfos:      file_token_metadata_proto_msgTypes,
	}.Build()
	File_token_metadata_proto = out.File
	file_token_metadata_proto_rawDesc = nil
	file_token_metadata_proto_goTypes = nil
	file_token_metadata_proto_depIdxs = nil
}
