// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: user-device.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDevicePairingInfo_Status int32

const (
	UserDevicePairingInfo_NONE     UserDevicePairingInfo_Status = 0
	UserDevicePairingInfo_WAITING  UserDevicePairingInfo_Status = 1
	UserDevicePairingInfo_PAIRING  UserDevicePairingInfo_Status = 2
	UserDevicePairingInfo_APPROVED UserDevicePairingInfo_Status = 3
)

// Enum value maps for UserDevicePairingInfo_Status.
var (
	UserDevicePairingInfo_Status_name = map[int32]string{
		0: "NONE",
		1: "WAITING",
		2: "PAIRING",
		3: "APPROVED",
	}
	UserDevicePairingInfo_Status_value = map[string]int32{
		"NONE":     0,
		"WAITING":  1,
		"PAIRING":  2,
		"APPROVED": 3,
	}
)

func (x UserDevicePairingInfo_Status) Enum() *UserDevicePairingInfo_Status {
	p := new(UserDevicePairingInfo_Status)
	*p = x
	return p
}

func (x UserDevicePairingInfo_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDevicePairingInfo_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_user_device_proto_enumTypes[0].Descriptor()
}

func (UserDevicePairingInfo_Status) Type() protoreflect.EnumType {
	return &file_user_device_proto_enumTypes[0]
}

func (x UserDevicePairingInfo_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDevicePairingInfo_Status.Descriptor instead.
func (UserDevicePairingInfo_Status) EnumDescriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{0, 0}
}

type UserDevicePairingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    UserDevicePairingInfo_Status `protobuf:"varint,1,opt,name=status,proto3,enum=tgvalidatord.UserDevicePairingInfo_Status" json:"status,omitempty"`
	PairingID string                       `protobuf:"bytes,2,opt,name=pairingID,proto3" json:"pairingID,omitempty"`
	ApiKey    string                       `protobuf:"bytes,3,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
}

func (x *UserDevicePairingInfo) Reset() {
	*x = UserDevicePairingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDevicePairingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDevicePairingInfo) ProtoMessage() {}

func (x *UserDevicePairingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDevicePairingInfo.ProtoReflect.Descriptor instead.
func (*UserDevicePairingInfo) Descriptor() ([]byte, []int) {
	return file_user_device_proto_rawDescGZIP(), []int{0}
}

func (x *UserDevicePairingInfo) GetStatus() UserDevicePairingInfo_Status {
	if x != nil {
		return x.Status
	}
	return UserDevicePairingInfo_NONE
}

func (x *UserDevicePairingInfo) GetPairingID() string {
	if x != nil {
		return x.PairingID
	}
	return ""
}

func (x *UserDevicePairingInfo) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_user_device_proto protoreflect.FileDescriptor

var file_user_device_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x67, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x64, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8d, 0x02, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x66, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x74, 0x67,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x22, 0x92, 0x41, 0x1f, 0x32, 0x1d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x20, 0x6f, 0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x70, 0x61, 0x69, 0x72,
	0x69, 0x6e, 0x67, 0x20, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41,
	0x49, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50, 0x52, 0x4f,
	0x56, 0x45, 0x44, 0x10, 0x03, 0x3a, 0x1a, 0x92, 0x41, 0x17, 0x0a, 0x15, 0xd2, 0x01, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0xd2, 0x01, 0x09, 0x70, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x49,
	0x44, 0x42, 0x23, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x75, 0x72, 0x75, 0x73, 0x68,
	0x71, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_device_proto_rawDescOnce sync.Once
	file_user_device_proto_rawDescData = file_user_device_proto_rawDesc
)

func file_user_device_proto_rawDescGZIP() []byte {
	file_user_device_proto_rawDescOnce.Do(func() {
		file_user_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_device_proto_rawDescData)
	})
	return file_user_device_proto_rawDescData
}

var file_user_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_device_proto_goTypes = []interface{}{
	(UserDevicePairingInfo_Status)(0), // 0: tgvalidatord.UserDevicePairingInfo.Status
	(*UserDevicePairingInfo)(nil),     // 1: tgvalidatord.UserDevicePairingInfo
}
var file_user_device_proto_depIdxs = []int32{
	0, // 0: tgvalidatord.UserDevicePairingInfo.status:type_name -> tgvalidatord.UserDevicePairingInfo.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_device_proto_init() }
func file_user_device_proto_init() {
	if File_user_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDevicePairingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_device_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_device_proto_goTypes,
		DependencyIndexes: file_user_device_proto_depIdxs,
		EnumInfos:         file_user_device_proto_enumTypes,
		MessageInfos:      file_user_device_proto_msgTypes,
	}.Build()
	File_user_device_proto = out.File
	file_user_device_proto_rawDesc = nil
	file_user_device_proto_goTypes = nil
	file_user_device_proto_depIdxs = nil
}
