/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiKeyVerificationType = {
    Hmac: 'HMAC',
    Ecdsa: 'ECDSA'
} as const;
export type ApiKeyVerificationType = typeof ApiKeyVerificationType[keyof typeof ApiKeyVerificationType];


export function instanceOfApiKeyVerificationType(value: any): boolean {
    for (const key in ApiKeyVerificationType) {
        if (Object.prototype.hasOwnProperty.call(ApiKeyVerificationType, key)) {
            if (ApiKeyVerificationType[key as keyof typeof ApiKeyVerificationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiKeyVerificationTypeFromJSON(json: any): ApiKeyVerificationType {
    return ApiKeyVerificationTypeFromJSONTyped(json, false);
}

export function ApiKeyVerificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyVerificationType {
    return json as ApiKeyVerificationType;
}

export function ApiKeyVerificationTypeToJSON(value?: ApiKeyVerificationType | null): any {
    return value as any;
}

export function ApiKeyVerificationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiKeyVerificationType {
    return value as ApiKeyVerificationType;
}

