/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StewardServiceCreateApiKeyBody
 */
export interface StewardServiceCreateApiKeyBody {
    /**
     * 
     * @type {Date}
     * @memberof StewardServiceCreateApiKeyBody
     */
    expiration?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof StewardServiceCreateApiKeyBody
     */
    roles?: Array<string>;
}

/**
 * Check if a given object implements the StewardServiceCreateApiKeyBody interface.
 */
export function instanceOfStewardServiceCreateApiKeyBody(value: object): value is StewardServiceCreateApiKeyBody {
    return true;
}

export function StewardServiceCreateApiKeyBodyFromJSON(json: any): StewardServiceCreateApiKeyBody {
    return StewardServiceCreateApiKeyBodyFromJSONTyped(json, false);
}

export function StewardServiceCreateApiKeyBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StewardServiceCreateApiKeyBody {
    if (json == null) {
        return json;
    }
    return {
        
        'expiration': json['expiration'] == null ? undefined : (new Date(json['expiration'])),
        'roles': json['roles'] == null ? undefined : json['roles'],
    };
}

  export function StewardServiceCreateApiKeyBodyToJSON(json: any): StewardServiceCreateApiKeyBody {
      return StewardServiceCreateApiKeyBodyToJSONTyped(json, false);
  }

  export function StewardServiceCreateApiKeyBodyToJSONTyped(value?: StewardServiceCreateApiKeyBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiration': value['expiration'] == null ? undefined : ((value['expiration']).toISOString()),
        'roles': value['roles'],
    };
}

