/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordApiKeyToken } from './TgvalidatordApiKeyToken';
import {
    TgvalidatordApiKeyTokenFromJSON,
    TgvalidatordApiKeyTokenFromJSONTyped,
    TgvalidatordApiKeyTokenToJSON,
    TgvalidatordApiKeyTokenToJSONTyped,
} from './TgvalidatordApiKeyToken';

/**
 * 
 * @export
 * @interface TgvalidatordCreateApiKeyReply
 */
export interface TgvalidatordCreateApiKeyReply {
    /**
     * 
     * @type {TgvalidatordApiKeyToken}
     * @memberof TgvalidatordCreateApiKeyReply
     */
    result?: TgvalidatordApiKeyToken;
}

/**
 * Check if a given object implements the TgvalidatordCreateApiKeyReply interface.
 */
export function instanceOfTgvalidatordCreateApiKeyReply(value: object): value is TgvalidatordCreateApiKeyReply {
    return true;
}

export function TgvalidatordCreateApiKeyReplyFromJSON(json: any): TgvalidatordCreateApiKeyReply {
    return TgvalidatordCreateApiKeyReplyFromJSONTyped(json, false);
}

export function TgvalidatordCreateApiKeyReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordCreateApiKeyReply {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : TgvalidatordApiKeyTokenFromJSON(json['result']),
    };
}

  export function TgvalidatordCreateApiKeyReplyToJSON(json: any): TgvalidatordCreateApiKeyReply {
      return TgvalidatordCreateApiKeyReplyToJSONTyped(json, false);
  }

  export function TgvalidatordCreateApiKeyReplyToJSONTyped(value?: TgvalidatordCreateApiKeyReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': TgvalidatordApiKeyTokenToJSON(value['result']),
    };
}

