/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordApiKey } from './TgvalidatordApiKey';
import {
    TgvalidatordApiKeyFromJSON,
    TgvalidatordApiKeyFromJSONTyped,
    TgvalidatordApiKeyToJSON,
    TgvalidatordApiKeyToJSONTyped,
} from './TgvalidatordApiKey';

/**
 * 
 * @export
 * @interface TgvalidatordListApiKeyReply
 */
export interface TgvalidatordListApiKeyReply {
    /**
     * 
     * @type {Array<TgvalidatordApiKey>}
     * @memberof TgvalidatordListApiKeyReply
     */
    result?: Array<TgvalidatordApiKey>;
}

/**
 * Check if a given object implements the TgvalidatordListApiKeyReply interface.
 */
export function instanceOfTgvalidatordListApiKeyReply(value: object): value is TgvalidatordListApiKeyReply {
    return true;
}

export function TgvalidatordListApiKeyReplyFromJSON(json: any): TgvalidatordListApiKeyReply {
    return TgvalidatordListApiKeyReplyFromJSONTyped(json, false);
}

export function TgvalidatordListApiKeyReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordListApiKeyReply {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TgvalidatordApiKeyFromJSON)),
    };
}

  export function TgvalidatordListApiKeyReplyToJSON(json: any): TgvalidatordListApiKeyReply {
      return TgvalidatordListApiKeyReplyToJSONTyped(json, false);
  }

  export function TgvalidatordListApiKeyReplyToJSONTyped(value?: TgvalidatordListApiKeyReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TgvalidatordApiKeyToJSON)),
    };
}

