/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordApiKey } from './TgvalidatordApiKey';
import {
    TgvalidatordApiKeyFromJSON,
    TgvalidatordApiKeyFromJSONTyped,
    TgvalidatordApiKeyToJSON,
    TgvalidatordApiKeyToJSONTyped,
} from './TgvalidatordApiKey';

/**
 * 
 * @export
 * @interface TgvalidatordApiKeyToken
 */
export interface TgvalidatordApiKeyToken {
    /**
     * 
     * @type {TgvalidatordApiKey}
     * @memberof TgvalidatordApiKeyToken
     */
    apiKey?: TgvalidatordApiKey;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordApiKeyToken
     */
    token?: string;
}

/**
 * Check if a given object implements the TgvalidatordApiKeyToken interface.
 */
export function instanceOfTgvalidatordApiKeyToken(value: object): value is TgvalidatordApiKeyToken {
    return true;
}

export function TgvalidatordApiKeyTokenFromJSON(json: any): TgvalidatordApiKeyToken {
    return TgvalidatordApiKeyTokenFromJSONTyped(json, false);
}

export function TgvalidatordApiKeyTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordApiKeyToken {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'] == null ? undefined : TgvalidatordApiKeyFromJSON(json['apiKey']),
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function TgvalidatordApiKeyTokenToJSON(json: any): TgvalidatordApiKeyToken {
      return TgvalidatordApiKeyTokenToJSONTyped(json, false);
  }

  export function TgvalidatordApiKeyTokenToJSONTyped(value?: TgvalidatordApiKeyToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKey': TgvalidatordApiKeyToJSON(value['apiKey']),
        'token': value['token'],
    };
}

