/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordRevealUserApiKeyReply
 */
export interface TgvalidatordRevealUserApiKeyReply {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordRevealUserApiKeyReply
     */
    apiKeyId?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordRevealUserApiKeyReply
     */
    secret?: string;
    /**
     * 
     * @type {Date}
     * @memberof TgvalidatordRevealUserApiKeyReply
     */
    creationDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TgvalidatordRevealUserApiKeyReply
     */
    revealDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof TgvalidatordRevealUserApiKeyReply
     */
    revealable?: boolean;
}

/**
 * Check if a given object implements the TgvalidatordRevealUserApiKeyReply interface.
 */
export function instanceOfTgvalidatordRevealUserApiKeyReply(value: object): value is TgvalidatordRevealUserApiKeyReply {
    return true;
}

export function TgvalidatordRevealUserApiKeyReplyFromJSON(json: any): TgvalidatordRevealUserApiKeyReply {
    return TgvalidatordRevealUserApiKeyReplyFromJSONTyped(json, false);
}

export function TgvalidatordRevealUserApiKeyReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordRevealUserApiKeyReply {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKeyId': json['apiKeyId'] == null ? undefined : json['apiKeyId'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'revealDate': json['revealDate'] == null ? undefined : (new Date(json['revealDate'])),
        'revealable': json['revealable'] == null ? undefined : json['revealable'],
    };
}

  export function TgvalidatordRevealUserApiKeyReplyToJSON(json: any): TgvalidatordRevealUserApiKeyReply {
      return TgvalidatordRevealUserApiKeyReplyToJSONTyped(json, false);
  }

  export function TgvalidatordRevealUserApiKeyReplyToJSONTyped(value?: TgvalidatordRevealUserApiKeyReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKeyId': value['apiKeyId'],
        'secret': value['secret'],
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
        'revealDate': value['revealDate'] == null ? undefined : ((value['revealDate']).toISOString()),
        'revealable': value['revealable'],
    };
}

