/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordCredentials
 */
export interface TgvalidatordCredentials {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCredentials
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCredentials
     */
    password: string;
    /**
     * Time-based One Time Password (2FA)
     * @type {string}
     * @memberof TgvalidatordCredentials
     */
    totp?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCredentials
     */
    username?: string;
}

/**
 * Check if a given object implements the TgvalidatordCredentials interface.
 */
export function instanceOfTgvalidatordCredentials(value: object): value is TgvalidatordCredentials {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function TgvalidatordCredentialsFromJSON(json: any): TgvalidatordCredentials {
    return TgvalidatordCredentialsFromJSONTyped(json, false);
}

export function TgvalidatordCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'],
        'totp': json['totp'] == null ? undefined : json['totp'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

  export function TgvalidatordCredentialsToJSON(json: any): TgvalidatordCredentials {
      return TgvalidatordCredentialsToJSONTyped(json, false);
  }

  export function TgvalidatordCredentialsToJSONTyped(value?: TgvalidatordCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'totp': value['totp'],
        'username': value['username'],
    };
}

