/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordApiKey
 */
export interface TgvalidatordApiKey {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordApiKey
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordApiKey
     */
    tenantId?: string;
    /**
     * 
     * @type {Date}
     * @memberof TgvalidatordApiKey
     */
    expirationDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TgvalidatordApiKey
     */
    creationDate?: Date;
}

/**
 * Check if a given object implements the TgvalidatordApiKey interface.
 */
export function instanceOfTgvalidatordApiKey(value: object): value is TgvalidatordApiKey {
    return true;
}

export function TgvalidatordApiKeyFromJSON(json: any): TgvalidatordApiKey {
    return TgvalidatordApiKeyFromJSONTyped(json, false);
}

export function TgvalidatordApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordApiKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tenantId': json['tenantId'] == null ? undefined : json['tenantId'],
        'expirationDate': json['expirationDate'] == null ? undefined : (new Date(json['expirationDate'])),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
    };
}

  export function TgvalidatordApiKeyToJSON(json: any): TgvalidatordApiKey {
      return TgvalidatordApiKeyToJSONTyped(json, false);
  }

  export function TgvalidatordApiKeyToJSONTyped(value?: TgvalidatordApiKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'expirationDate': value['expirationDate'] == null ? undefined : ((value['expirationDate']).toISOString()),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
    };
}

