/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ApiKeyVerificationType the model 'ApiKeyVerificationType'
type ApiKeyVerificationType string

// List of ApiKeyVerificationType
const (
	APIKEYVERIFICATIONTYPE_HMAC  ApiKeyVerificationType = "HMAC"
	APIKEYVERIFICATIONTYPE_ECDSA ApiKeyVerificationType = "ECDSA"
)

// All allowed values of ApiKeyVerificationType enum
var AllowedApiKeyVerificationTypeEnumValues = []ApiKeyVerificationType{
	"HMAC",
	"ECDSA",
}

func (v *ApiKeyVerificationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ApiKeyVerificationType(value)
	for _, existing := range AllowedApiKeyVerificationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ApiKeyVerificationType", value)
}

// NewApiKeyVerificationTypeFromValue returns a pointer to a valid ApiKeyVerificationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewApiKeyVerificationTypeFromValue(v string) (*ApiKeyVerificationType, error) {
	ev := ApiKeyVerificationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ApiKeyVerificationType: valid values are %v", v, AllowedApiKeyVerificationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ApiKeyVerificationType) IsValid() bool {
	for _, existing := range AllowedApiKeyVerificationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ApiKeyVerificationType value
func (v ApiKeyVerificationType) Ptr() *ApiKeyVerificationType {
	return &v
}

type NullableApiKeyVerificationType struct {
	value *ApiKeyVerificationType
	isSet bool
}

func (v NullableApiKeyVerificationType) Get() *ApiKeyVerificationType {
	return v.value
}

func (v *NullableApiKeyVerificationType) Set(val *ApiKeyVerificationType) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyVerificationType) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyVerificationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyVerificationType(val *ApiKeyVerificationType) *NullableApiKeyVerificationType {
	return &NullableApiKeyVerificationType{value: val, isSet: true}
}

func (v NullableApiKeyVerificationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyVerificationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
