// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: apikey.proto
// Protobuf Java Version: 4.29.3

package com.taurushq.sdk.protect.proto.v1;

public final class Apikey {
  private Apikey() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Apikey.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tgvalidatord.ApiKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>uint64 tenantId = 2;</code>
     * @return The tenantId.
     */
    long getTenantId();

    /**
     * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
     * @return Whether the expirationDate field is set.
     */
    boolean hasExpirationDate();
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
     * @return The expirationDate.
     */
    com.google.protobuf.Timestamp getExpirationDate();
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp creationDate = 4;</code>
     * @return Whether the creationDate field is set.
     */
    boolean hasCreationDate();
    /**
     * <code>.google.protobuf.Timestamp creationDate = 4;</code>
     * @return The creationDate.
     */
    com.google.protobuf.Timestamp getCreationDate();
    /**
     * <code>.google.protobuf.Timestamp creationDate = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreationDateOrBuilder();
  }
  /**
   * Protobuf type {@code tgvalidatord.ApiKey}
   */
  public static final class ApiKey extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tgvalidatord.ApiKey)
      ApiKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ApiKey.class.getName());
    }
    // Use ApiKey.newBuilder() to construct.
    private ApiKey(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ApiKey() {
      id_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.class, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANTID_FIELD_NUMBER = 2;
    private long tenantId_ = 0L;
    /**
     * <code>uint64 tenantId = 2;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public long getTenantId() {
      return tenantId_;
    }

    public static final int EXPIRATIONDATE_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp expirationDate_;
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
     * @return Whether the expirationDate field is set.
     */
    @java.lang.Override
    public boolean hasExpirationDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
     * @return The expirationDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getExpirationDate() {
      return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder() {
      return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
    }

    public static final int CREATIONDATE_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp creationDate_;
    /**
     * <code>.google.protobuf.Timestamp creationDate = 4;</code>
     * @return Whether the creationDate field is set.
     */
    @java.lang.Override
    public boolean hasCreationDate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp creationDate = 4;</code>
     * @return The creationDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreationDate() {
      return creationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creationDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp creationDate = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreationDateOrBuilder() {
      return creationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creationDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (tenantId_ != 0L) {
        output.writeUInt64(2, tenantId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getExpirationDate());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getCreationDate());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (tenantId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, tenantId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getExpirationDate());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCreationDate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey)) {
        return super.equals(obj);
      }
      com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey other = (com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getTenantId()
          != other.getTenantId()) return false;
      if (hasExpirationDate() != other.hasExpirationDate()) return false;
      if (hasExpirationDate()) {
        if (!getExpirationDate()
            .equals(other.getExpirationDate())) return false;
      }
      if (hasCreationDate() != other.hasCreationDate()) return false;
      if (hasCreationDate()) {
        if (!getCreationDate()
            .equals(other.getCreationDate())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TENANTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTenantId());
      if (hasExpirationDate()) {
        hash = (37 * hash) + EXPIRATIONDATE_FIELD_NUMBER;
        hash = (53 * hash) + getExpirationDate().hashCode();
      }
      if (hasCreationDate()) {
        hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
        hash = (53 * hash) + getCreationDate().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tgvalidatord.ApiKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tgvalidatord.ApiKey)
        com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.class, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder.class);
      }

      // Construct using com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getExpirationDateFieldBuilder();
          getCreationDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        tenantId_ = 0L;
        expirationDate_ = null;
        if (expirationDateBuilder_ != null) {
          expirationDateBuilder_.dispose();
          expirationDateBuilder_ = null;
        }
        creationDate_ = null;
        if (creationDateBuilder_ != null) {
          creationDateBuilder_.dispose();
          creationDateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKey_descriptor;
      }

      @java.lang.Override
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey getDefaultInstanceForType() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance();
      }

      @java.lang.Override
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey build() {
        com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey buildPartial() {
        com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey result = new com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tenantId_ = tenantId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.expirationDate_ = expirationDateBuilder_ == null
              ? expirationDate_
              : expirationDateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.creationDate_ = creationDateBuilder_ == null
              ? creationDate_
              : creationDateBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey) {
          return mergeFrom((com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey other) {
        if (other == com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTenantId() != 0L) {
          setTenantId(other.getTenantId());
        }
        if (other.hasExpirationDate()) {
          mergeExpirationDate(other.getExpirationDate());
        }
        if (other.hasCreationDate()) {
          mergeCreationDate(other.getCreationDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                tenantId_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getExpirationDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getCreationDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long tenantId_ ;
      /**
       * <code>uint64 tenantId = 2;</code>
       * @return The tenantId.
       */
      @java.lang.Override
      public long getTenantId() {
        return tenantId_;
      }
      /**
       * <code>uint64 tenantId = 2;</code>
       * @param value The tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantId(long value) {

        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 tenantId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tenantId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp expirationDate_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expirationDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       * @return Whether the expirationDate field is set.
       */
      public boolean hasExpirationDate() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       * @return The expirationDate.
       */
      public com.google.protobuf.Timestamp getExpirationDate() {
        if (expirationDateBuilder_ == null) {
          return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
        } else {
          return expirationDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      public Builder setExpirationDate(com.google.protobuf.Timestamp value) {
        if (expirationDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expirationDate_ = value;
        } else {
          expirationDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      public Builder setExpirationDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (expirationDateBuilder_ == null) {
          expirationDate_ = builderForValue.build();
        } else {
          expirationDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      public Builder mergeExpirationDate(com.google.protobuf.Timestamp value) {
        if (expirationDateBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            expirationDate_ != null &&
            expirationDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getExpirationDateBuilder().mergeFrom(value);
          } else {
            expirationDate_ = value;
          }
        } else {
          expirationDateBuilder_.mergeFrom(value);
        }
        if (expirationDate_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      public Builder clearExpirationDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expirationDate_ = null;
        if (expirationDateBuilder_ != null) {
          expirationDateBuilder_.dispose();
          expirationDateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getExpirationDateBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getExpirationDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder() {
        if (expirationDateBuilder_ != null) {
          return expirationDateBuilder_.getMessageOrBuilder();
        } else {
          return expirationDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp expirationDate = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getExpirationDateFieldBuilder() {
        if (expirationDateBuilder_ == null) {
          expirationDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getExpirationDate(),
                  getParentForChildren(),
                  isClean());
          expirationDate_ = null;
        }
        return expirationDateBuilder_;
      }

      private com.google.protobuf.Timestamp creationDate_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> creationDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       * @return Whether the creationDate field is set.
       */
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       * @return The creationDate.
       */
      public com.google.protobuf.Timestamp getCreationDate() {
        if (creationDateBuilder_ == null) {
          return creationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creationDate_;
        } else {
          return creationDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      public Builder setCreationDate(com.google.protobuf.Timestamp value) {
        if (creationDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          creationDate_ = value;
        } else {
          creationDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      public Builder setCreationDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (creationDateBuilder_ == null) {
          creationDate_ = builderForValue.build();
        } else {
          creationDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      public Builder mergeCreationDate(com.google.protobuf.Timestamp value) {
        if (creationDateBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            creationDate_ != null &&
            creationDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreationDateBuilder().mergeFrom(value);
          } else {
            creationDate_ = value;
          }
        } else {
          creationDateBuilder_.mergeFrom(value);
        }
        if (creationDate_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      public Builder clearCreationDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        creationDate_ = null;
        if (creationDateBuilder_ != null) {
          creationDateBuilder_.dispose();
          creationDateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreationDateBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getCreationDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreationDateOrBuilder() {
        if (creationDateBuilder_ != null) {
          return creationDateBuilder_.getMessageOrBuilder();
        } else {
          return creationDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : creationDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp creationDate = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreationDateFieldBuilder() {
        if (creationDateBuilder_ == null) {
          creationDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreationDate(),
                  getParentForChildren(),
                  isClean());
          creationDate_ = null;
        }
        return creationDateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tgvalidatord.ApiKey)
    }

    // @@protoc_insertion_point(class_scope:tgvalidatord.ApiKey)
    private static final com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey();
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiKey>
        PARSER = new com.google.protobuf.AbstractParser<ApiKey>() {
      @java.lang.Override
      public ApiKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApiKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiKeyTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tgvalidatord.ApiKeyToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
     * @return Whether the apiKey field is set.
     */
    boolean hasApiKey();
    /**
     * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
     * @return The apiKey.
     */
    com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey getApiKey();
    /**
     * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
     */
    com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder getApiKeyOrBuilder();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code tgvalidatord.ApiKeyToken}
   */
  public static final class ApiKeyToken extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tgvalidatord.ApiKeyToken)
      ApiKeyTokenOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ApiKeyToken.class.getName());
    }
    // Use ApiKeyToken.newBuilder() to construct.
    private ApiKeyToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ApiKeyToken() {
      token_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKeyToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKeyToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.class, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.Builder.class);
    }

    private int bitField0_;
    public static final int APIKEY_FIELD_NUMBER = 1;
    private com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey apiKey_;
    /**
     * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
     * @return Whether the apiKey field is set.
     */
    @java.lang.Override
    public boolean hasApiKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
     * @return The apiKey.
     */
    @java.lang.Override
    public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey getApiKey() {
      return apiKey_ == null ? com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance() : apiKey_;
    }
    /**
     * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
     */
    @java.lang.Override
    public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder getApiKeyOrBuilder() {
      return apiKey_ == null ? com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance() : apiKey_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getApiKey());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, token_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getApiKey());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken)) {
        return super.equals(obj);
      }
      com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken other = (com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken) obj;

      if (hasApiKey() != other.hasApiKey()) return false;
      if (hasApiKey()) {
        if (!getApiKey()
            .equals(other.getApiKey())) return false;
      }
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasApiKey()) {
        hash = (37 * hash) + APIKEY_FIELD_NUMBER;
        hash = (53 * hash) + getApiKey().hashCode();
      }
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tgvalidatord.ApiKeyToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tgvalidatord.ApiKeyToken)
        com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKeyToken_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKeyToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.class, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.Builder.class);
      }

      // Construct using com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getApiKeyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        apiKey_ = null;
        if (apiKeyBuilder_ != null) {
          apiKeyBuilder_.dispose();
          apiKeyBuilder_ = null;
        }
        token_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.internal_static_tgvalidatord_ApiKeyToken_descriptor;
      }

      @java.lang.Override
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken getDefaultInstanceForType() {
        return com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.getDefaultInstance();
      }

      @java.lang.Override
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken build() {
        com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken buildPartial() {
        com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken result = new com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.apiKey_ = apiKeyBuilder_ == null
              ? apiKey_
              : apiKeyBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.token_ = token_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken) {
          return mergeFrom((com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken other) {
        if (other == com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken.getDefaultInstance()) return this;
        if (other.hasApiKey()) {
          mergeApiKey(other.getApiKey());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getApiKeyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey apiKey_;
      private com.google.protobuf.SingleFieldBuilder<
          com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder> apiKeyBuilder_;
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       * @return Whether the apiKey field is set.
       */
      public boolean hasApiKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       * @return The apiKey.
       */
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey getApiKey() {
        if (apiKeyBuilder_ == null) {
          return apiKey_ == null ? com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance() : apiKey_;
        } else {
          return apiKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      public Builder setApiKey(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey value) {
        if (apiKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          apiKey_ = value;
        } else {
          apiKeyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      public Builder setApiKey(
          com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder builderForValue) {
        if (apiKeyBuilder_ == null) {
          apiKey_ = builderForValue.build();
        } else {
          apiKeyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      public Builder mergeApiKey(com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey value) {
        if (apiKeyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            apiKey_ != null &&
            apiKey_ != com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance()) {
            getApiKeyBuilder().mergeFrom(value);
          } else {
            apiKey_ = value;
          }
        } else {
          apiKeyBuilder_.mergeFrom(value);
        }
        if (apiKey_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      public Builder clearApiKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        apiKey_ = null;
        if (apiKeyBuilder_ != null) {
          apiKeyBuilder_.dispose();
          apiKeyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder getApiKeyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getApiKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder getApiKeyOrBuilder() {
        if (apiKeyBuilder_ != null) {
          return apiKeyBuilder_.getMessageOrBuilder();
        } else {
          return apiKey_ == null ?
              com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.getDefaultInstance() : apiKey_;
        }
      }
      /**
       * <code>.tgvalidatord.ApiKey apiKey = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder> 
          getApiKeyFieldBuilder() {
        if (apiKeyBuilder_ == null) {
          apiKeyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKey.Builder, com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyOrBuilder>(
                  getApiKey(),
                  getParentForChildren(),
                  isClean());
          apiKey_ = null;
        }
        return apiKeyBuilder_;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tgvalidatord.ApiKeyToken)
    }

    // @@protoc_insertion_point(class_scope:tgvalidatord.ApiKeyToken)
    private static final com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken();
    }

    public static com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiKeyToken>
        PARSER = new com.google.protobuf.AbstractParser<ApiKeyToken>() {
      @java.lang.Override
      public ApiKeyToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApiKeyToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiKeyToken> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taurushq.sdk.protect.proto.v1.Apikey.ApiKeyToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tgvalidatord_ApiKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tgvalidatord_ApiKey_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tgvalidatord_ApiKeyToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tgvalidatord_ApiKeyToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014apikey.proto\022\014tgvalidatord\032\037google/pro" +
      "tobuf/timestamp.proto\"\214\001\n\006ApiKey\022\n\n\002id\030\001" +
      " \001(\t\022\020\n\010tenantId\030\002 \001(\004\0222\n\016expirationDate" +
      "\030\003 \001(\0132\032.google.protobuf.Timestamp\0220\n\014cr" +
      "eationDate\030\004 \001(\0132\032.google.protobuf.Times" +
      "tamp\"B\n\013ApiKeyToken\022$\n\006apiKey\030\001 \001(\0132\024.tg" +
      "validatord.ApiKey\022\r\n\005token\030\002 \001(\tB#\n!com." +
      "taurushq.sdk.protect.proto.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tgvalidatord_ApiKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tgvalidatord_ApiKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tgvalidatord_ApiKey_descriptor,
        new java.lang.String[] { "Id", "TenantId", "ExpirationDate", "CreationDate", });
    internal_static_tgvalidatord_ApiKeyToken_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tgvalidatord_ApiKeyToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tgvalidatord_ApiKeyToken_descriptor,
        new java.lang.String[] { "ApiKey", "Token", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
