/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * TgvalidatordRevealUserApiKeyReply
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-30T08:14:18.502158138Z[GMT]", comments = "Generator version: 7.9.0")
public class TgvalidatordRevealUserApiKeyReply {
  public static final String SERIALIZED_NAME_API_KEY_ID = "apiKeyId";
  @SerializedName(SERIALIZED_NAME_API_KEY_ID)
  private String apiKeyId;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creationDate";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private OffsetDateTime creationDate;

  public static final String SERIALIZED_NAME_REVEAL_DATE = "revealDate";
  @SerializedName(SERIALIZED_NAME_REVEAL_DATE)
  private OffsetDateTime revealDate;

  public static final String SERIALIZED_NAME_REVEALABLE = "revealable";
  @SerializedName(SERIALIZED_NAME_REVEALABLE)
  private Boolean revealable;

  public TgvalidatordRevealUserApiKeyReply() {
  }

  public TgvalidatordRevealUserApiKeyReply apiKeyId(String apiKeyId) {
    this.apiKeyId = apiKeyId;
    return this;
  }

  /**
   * Get apiKeyId
   * @return apiKeyId
   */
  @javax.annotation.Nullable
  public String getApiKeyId() {
    return apiKeyId;
  }

  public void setApiKeyId(String apiKeyId) {
    this.apiKeyId = apiKeyId;
  }


  public TgvalidatordRevealUserApiKeyReply secret(String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * Get secret
   * @return secret
   */
  @javax.annotation.Nullable
  public String getSecret() {
    return secret;
  }

  public void setSecret(String secret) {
    this.secret = secret;
  }


  public TgvalidatordRevealUserApiKeyReply creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * Get creationDate
   * @return creationDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }


  public TgvalidatordRevealUserApiKeyReply revealDate(OffsetDateTime revealDate) {
    this.revealDate = revealDate;
    return this;
  }

  /**
   * Get revealDate
   * @return revealDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getRevealDate() {
    return revealDate;
  }

  public void setRevealDate(OffsetDateTime revealDate) {
    this.revealDate = revealDate;
  }


  public TgvalidatordRevealUserApiKeyReply revealable(Boolean revealable) {
    this.revealable = revealable;
    return this;
  }

  /**
   * Get revealable
   * @return revealable
   */
  @javax.annotation.Nullable
  public Boolean getRevealable() {
    return revealable;
  }

  public void setRevealable(Boolean revealable) {
    this.revealable = revealable;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TgvalidatordRevealUserApiKeyReply instance itself
   */
  public TgvalidatordRevealUserApiKeyReply putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TgvalidatordRevealUserApiKeyReply tgvalidatordRevealUserApiKeyReply = (TgvalidatordRevealUserApiKeyReply) o;
    return Objects.equals(this.apiKeyId, tgvalidatordRevealUserApiKeyReply.apiKeyId) &&
        Objects.equals(this.secret, tgvalidatordRevealUserApiKeyReply.secret) &&
        Objects.equals(this.creationDate, tgvalidatordRevealUserApiKeyReply.creationDate) &&
        Objects.equals(this.revealDate, tgvalidatordRevealUserApiKeyReply.revealDate) &&
        Objects.equals(this.revealable, tgvalidatordRevealUserApiKeyReply.revealable)&&
        Objects.equals(this.additionalProperties, tgvalidatordRevealUserApiKeyReply.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKeyId, secret, creationDate, revealDate, revealable, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TgvalidatordRevealUserApiKeyReply {\n");
    sb.append("    apiKeyId: ").append(toIndentedString(apiKeyId)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    revealDate: ").append(toIndentedString(revealDate)).append("\n");
    sb.append("    revealable: ").append(toIndentedString(revealable)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("apiKeyId");
    openapiFields.add("secret");
    openapiFields.add("creationDate");
    openapiFields.add("revealDate");
    openapiFields.add("revealable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TgvalidatordRevealUserApiKeyReply
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TgvalidatordRevealUserApiKeyReply.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TgvalidatordRevealUserApiKeyReply is not found in the empty JSON string", TgvalidatordRevealUserApiKeyReply.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("apiKeyId") != null && !jsonObj.get("apiKeyId").isJsonNull()) && !jsonObj.get("apiKeyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `apiKeyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("apiKeyId").toString()));
      }
      if ((jsonObj.get("secret") != null && !jsonObj.get("secret").isJsonNull()) && !jsonObj.get("secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secret").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TgvalidatordRevealUserApiKeyReply.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TgvalidatordRevealUserApiKeyReply' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TgvalidatordRevealUserApiKeyReply> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TgvalidatordRevealUserApiKeyReply.class));

       return (TypeAdapter<T>) new TypeAdapter<TgvalidatordRevealUserApiKeyReply>() {
           @Override
           public void write(JsonWriter out, TgvalidatordRevealUserApiKeyReply value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TgvalidatordRevealUserApiKeyReply read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             TgvalidatordRevealUserApiKeyReply instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TgvalidatordRevealUserApiKeyReply given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TgvalidatordRevealUserApiKeyReply
   * @throws IOException if the JSON string is invalid with respect to TgvalidatordRevealUserApiKeyReply
   */
  public static TgvalidatordRevealUserApiKeyReply fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TgvalidatordRevealUserApiKeyReply.class);
  }

  /**
   * Convert an instance of TgvalidatordRevealUserApiKeyReply to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

