# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apikey.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61pikey.proto\x12\x0ctgvalidatord\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n\x06\x41piKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08tenantId\x18\x02 \x01(\x04\x12\x32\n\x0e\x65xpirationDate\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63reationDate\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"B\n\x0b\x41piKeyToken\x12$\n\x06\x61piKey\x18\x01 \x01(\x0b\x32\x14.tgvalidatord.ApiKey\x12\r\n\x05token\x18\x02 \x01(\tB#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apikey_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _APIKEY._serialized_start=64
  _APIKEY._serialized_end=204
  _APIKEYTOKEN._serialized_start=206
  _APIKEYTOKEN._serialized_end=272
# @@protoc_insertion_point(module_scope)
