# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: change.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63hange.proto\x12\x0ctgvalidatord\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x99\x06\n\x06\x43hange\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08tenantId\x18\x02 \x01(\x04\x12\x11\n\tcreatorId\x18\x03 \x01(\x04\x12h\n\x06\x61\x63tion\x18\x04 \x01(\tBX\x92\x41U2SCan be one of the following: `create` `update` `delete` `resetpassword` `resettotp`\x12\x10\n\x08\x65ntityId\x18\x05 \x01(\x04\x12\xb1\x01\n\x06\x65ntity\x18\x06 \x01(\tB\xa0\x01\x92\x41\x9c\x01\x32\x99\x01\x43\x61n be one of the following: `user` `group` `usergroup` `businessrule` `exchange` `price` `action` `feepayer` `securitydomain` `taurusnetworkparticipant`\x12Z\n\x07\x63hanges\x18\x07 \x03(\x0b\x32!.tgvalidatord.Change.ChangesEntryB&\x92\x41#2!A map of the change set desired. \x12\x30\n\x0c\x63reationDate\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\x07\x63omment\x18\t \x01(\tB)\x92\x41&2$An optional comment about the change\x12I\n\nentityUUID\x18\n \x01(\tB5\x92\x41\x32\x32)Identification for entities that use UUID\xa2\x02\x04uuid\x12\x19\n\x11\x63reatorExternalId\x18\x0b \x01(\t\x1a.\n\x0c\x43hangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x06Status\x12\r\n\tUndefined\x10\x00\x12\x0b\n\x07\x43reated\x10\x01\x12\x0c\n\x08\x41pproved\x10\x02\x12\x0c\n\x08Rejected\x10\x03\x12\x0c\n\x08\x43\x61nceled\x10\x04\x42#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'change_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _CHANGE_CHANGESENTRY._options = None
  _CHANGE_CHANGESENTRY._serialized_options = b'8\001'
  _CHANGE.fields_by_name['action']._options = None
  _CHANGE.fields_by_name['action']._serialized_options = b'\222AU2SCan be one of the following: `create` `update` `delete` `resetpassword` `resettotp`'
  _CHANGE.fields_by_name['entity']._options = None
  _CHANGE.fields_by_name['entity']._serialized_options = b'\222A\234\0012\231\001Can be one of the following: `user` `group` `usergroup` `businessrule` `exchange` `price` `action` `feepayer` `securitydomain` `taurusnetworkparticipant`'
  _CHANGE.fields_by_name['changes']._options = None
  _CHANGE.fields_by_name['changes']._serialized_options = b'\222A#2!A map of the change set desired. '
  _CHANGE.fields_by_name['comment']._options = None
  _CHANGE.fields_by_name['comment']._serialized_options = b'\222A&2$An optional comment about the change'
  _CHANGE.fields_by_name['entityUUID']._options = None
  _CHANGE.fields_by_name['entityUUID']._serialized_options = b'\222A22)Identification for entities that use UUID\242\002\004uuid'
  _CHANGE._serialized_start=112
  _CHANGE._serialized_end=905
  _CHANGE_CHANGESENTRY._serialized_start=779
  _CHANGE_CHANGESENTRY._serialized_end=825
  _CHANGE_STATUS._serialized_start=827
  _CHANGE_STATUS._serialized_end=905
# @@protoc_insertion_point(module_scope)
