# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credentials.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63redentials.proto\x12\x0ctgvalidatord\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8d\x01\n\x0b\x43redentials\x12\x11\n\x05\x65mail\x18\x01 \x01(\tB\x02\x18\x01\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x35\n\x04totp\x18\x03 \x01(\tB\'\x92\x41$2\"Time-based One Time Password (2FA)\x12\x10\n\x08username\x18\x04 \x01(\t:\x10\x92\x41\r\n\x0b\xd2\x01\x08password\"P\n\x0fSAMLAuthRequest\x12\r\n\x05index\x18\x01 \x01(\t\x12\x1c\n\x14signedTrackedRequest\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"3\n\x10SAMLAuthRedirect\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\"\x1c\n\x0bSAMLSession\x12\r\n\x05token\x18\x01 \x01(\t\">\n\x0cOIDCLocation\x12\x10\n\x08location\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"\x1c\n\x0bOIDCSession\x12\r\n\x05token\x18\x01 \x01(\tB#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credentials_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _CREDENTIALS.fields_by_name['email']._options = None
  _CREDENTIALS.fields_by_name['email']._serialized_options = b'\030\001'
  _CREDENTIALS.fields_by_name['totp']._options = None
  _CREDENTIALS.fields_by_name['totp']._serialized_options = b'\222A$2\"Time-based One Time Password (2FA)'
  _CREDENTIALS._options = None
  _CREDENTIALS._serialized_options = b'\222A\r\n\013\322\001\010password'
  _CREDENTIALS._serialized_start=84
  _CREDENTIALS._serialized_end=225
  _SAMLAUTHREQUEST._serialized_start=227
  _SAMLAUTHREQUEST._serialized_end=307
  _SAMLAUTHREDIRECT._serialized_start=309
  _SAMLAUTHREDIRECT._serialized_end=360
  _SAMLSESSION._serialized_start=362
  _SAMLSESSION._serialized_end=390
  _OIDCLOCATION._serialized_start=392
  _OIDCLOCATION._serialized_end=454
  _OIDCSESSION._serialized_start=456
  _OIDCSESSION._serialized_end=484
# @@protoc_insertion_point(module_scope)
