# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x0ctgvalidatord\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8c\x01\n\x0c\x43lientStatus\x12\x10\n\x08hostPort\x18\x01 \x01(\t\x12-\n\tconnected\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12,\n\x08lastPing\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xfb\x01\n\x0cHealthReport\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x38\n\x07results\x18\x06 \x03(\x0b\x32\'.tgvalidatord.HealthReport.ResultsEntry\x12\x31\n\rvaultdClients\x18\x07 \x03(\x0b\x32\x1a.tgvalidatord.ClientStatus\x1a.\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x02\n\x06Health\x12\x10\n\x08tenantId\x18\x01 \x01(\x04\x12\x15\n\rcomponentName\x18\x02 \x01(\t\x12\x13\n\x0b\x63omponentId\x18\x03 \x01(\t\x12\r\n\x05group\x18\x04 \x01(\t\x12\x13\n\x0bhealthCheck\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12*\n\x06report\x18\x07 \x01(\x0b\x32\x1a.tgvalidatord.HealthReport\x12\x32\n\x0elastUpdateDate\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0evalidUntilDate\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"9\n\x0bHealthGroup\x12*\n\x0chealthChecks\x18\x01 \x03(\x0b\x32\x14.tgvalidatord.Health\"\x96\x01\n\x0fHealthComponent\x12\x39\n\x06groups\x18\x01 \x03(\x0b\x32).tgvalidatord.HealthComponent.GroupsEntry\x1aH\n\x0bGroupsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.tgvalidatord.HealthGroup:\x02\x38\x01\x42#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _HEALTHREPORT_RESULTSENTRY._options = None
  _HEALTHREPORT_RESULTSENTRY._serialized_options = b'8\001'
  _HEALTHCOMPONENT_GROUPSENTRY._options = None
  _HEALTHCOMPONENT_GROUPSENTRY._serialized_options = b'8\001'
  _CLIENTSTATUS._serialized_start=96
  _CLIENTSTATUS._serialized_end=236
  _HEALTHREPORT._serialized_start=239
  _HEALTHREPORT._serialized_end=490
  _HEALTHREPORT_RESULTSENTRY._serialized_start=444
  _HEALTHREPORT_RESULTSENTRY._serialized_end=490
  _HEALTH._serialized_start=493
  _HEALTH._serialized_end=763
  _HEALTHGROUP._serialized_start=765
  _HEALTHGROUP._serialized_end=822
  _HEALTHCOMPONENT._serialized_start=825
  _HEALTHCOMPONENT._serialized_end=975
  _HEALTHCOMPONENT_GROUPSENTRY._serialized_start=903
  _HEALTHCOMPONENT_GROUPSENTRY._serialized_end=975
# @@protoc_insertion_point(module_scope)
