# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x0ctgvalidatord\x1a\x1cgoogle/protobuf/struct.proto\"Z\n\x08Metadata\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\'\n\x07payload\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\x12\x17\n\x0fpayloadAsString\x18\x03 \x01(\tB#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _METADATA._serialized_start=62
  _METADATA._serialized_end=152
# @@protoc_insertion_point(module_scope)
