# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import currency_pb2 as currency__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrule.proto\x12\x0ctgvalidatord\x1a\x0e\x63urrency.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x02\n\x0c\x42usinessRule\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08tenantId\x18\x02 \x01(\x04\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x14\n\x08walletId\x18\x04 \x01(\x04\x42\x02\x18\x01\x12\x0f\n\x07ruleKey\x18\x05 \x01(\t\x12\x11\n\truleValue\x18\x06 \x01(\t\x12\x11\n\truleGroup\x18\x07 \x01(\t\x12\x17\n\x0fruleDescription\x18\x08 \x01(\t\x12\x16\n\x0eruleValidation\x18\t \x01(\t\x12\x15\n\taddressId\x18\n \x01(\x04\x42\x02\x18\x01\x12,\n\x0c\x63urrencyInfo\x18\x0b \x01(\x0b\x32\x16.tgvalidatord.Currency\x12\x12\n\nentityType\x18\x0c \x01(\t\x12\x10\n\x08\x65ntityID\x18\r \x01(\t\"\xff\x02\n\x05Rules\x12\x16\n\x0erulesContainer\x18\x01 \x01(\t\x12\x38\n\x0frulesSignatures\x18\x02 \x03(\x0b\x32\x1f.tgvalidatord.RuleUserSignature\x12\x0e\n\x06locked\x18\x03 \x01(\x08\x12\x30\n\x0c\x63reationDate\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdateDate\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x06trails\x18\x06 \x03(\x0b\x32\x19.tgvalidatord.Rules.Trail\x1a\x86\x01\n\x05Trail\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06userId\x18\x02 \x01(\x04\x12\x16\n\x0e\x65xternalUserId\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12(\n\x04\x64\x61te\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"6\n\x11RuleUserSignature\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\tB#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rule_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _BUSINESSRULE.fields_by_name['walletId']._options = None
  _BUSINESSRULE.fields_by_name['walletId']._serialized_options = b'\030\001'
  _BUSINESSRULE.fields_by_name['addressId']._options = None
  _BUSINESSRULE.fields_by_name['addressId']._serialized_options = b'\030\001'
  _BUSINESSRULE._serialized_start=78
  _BUSINESSRULE._serialized_end=373
  _RULES._serialized_start=376
  _RULES._serialized_end=759
  _RULES_TRAIL._serialized_start=625
  _RULES_TRAIL._serialized_end=759
  _RULEUSERSIGNATURE._serialized_start=761
  _RULEUSERSIGNATURE._serialized_end=815
# @@protoc_insertion_point(module_scope)
