# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xtzbaker-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from . import xtzbaker_pb2 as xtzbaker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16xtzbaker-service.proto\x12\x0ctgvalidatord\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x0extzbaker.proto\"6\n\x12GetXTZBakerRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07network\x18\x02 \x01(\t\":\n\x10GetXTZBakerReply\x12&\n\x06result\x18\x01 \x01(\x0b\x32\x16.tgvalidatord.XTZBaker2\xec\x01\n\x0fXTZBakerService\x12\xd8\x01\n\x0bGetXTZBaker\x12 .tgvalidatord.GetXTZBakerRequest\x1a\x1e.tgvalidatord.GetXTZBakerReply\"\x86\x01\x82\xd3\xe4\x93\x02,\x12*/api/rest/v1/xtzbakers/{network}/{address}\x92\x41Q\n\rRequests: XTZ\x12\rGet XTZ baker\x1a\x31This endpoint returns the baker of an XTZ addressB\xd1\x03\n!com.taurushq.sdk.protect.proto.v1\x92\x41\xaa\x03\x12\x91\x01\n\x1etg-validatord xtzbaker service\"j\n\x1etg-validatord xtzbaker service\x12,https://github.com/taurusgroup/tg-validatord\x1a\x1a\x64\x65velopment@taurusgroup.ch2\x03\x31.0*\x02\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonR5\n\x03\x34\x30\x31\x12.\n,Returned when the user is not authenticated.RI\n\x03\x34\x30\x33\x12\x42\n@Returned when the user is not authorized to access the resource.R;\n\x03\x34\x30\x34\x12\x34\n*Returned when the resource does not exist.\x12\x06\n\x04\x9a\x02\x01\x07Z\x1f\n\x1d\n\x06\x42\x65\x61rer\x12\x13\x08\x02\x1a\rAuthorization \x02\x62\x0c\n\n\n\x06\x42\x65\x61rer\x12\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xtzbaker_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1\222A\252\003\022\221\001\n\036tg-validatord xtzbaker service\"j\n\036tg-validatord xtzbaker service\022,https://github.com/taurusgroup/tg-validatord\032\032development@taurusgroup.ch2\0031.0*\002\001\0022\020application/json:\020application/jsonR5\n\003401\022.\n,Returned when the user is not authenticated.RI\n\003403\022B\n@Returned when the user is not authorized to access the resource.R;\n\003404\0224\n*Returned when the resource does not exist.\022\006\n\004\232\002\001\007Z\037\n\035\n\006Bearer\022\023\010\002\032\rAuthorization \002b\014\n\n\n\006Bearer\022\000'
  _XTZBAKERSERVICE.methods_by_name['GetXTZBaker']._options = None
  _XTZBAKERSERVICE.methods_by_name['GetXTZBaker']._serialized_options = b'\202\323\344\223\002,\022*/api/rest/v1/xtzbakers/{network}/{address}\222AQ\n\rRequests: XTZ\022\rGet XTZ baker\0321This endpoint returns the baker of an XTZ address'
  _GETXTZBAKERREQUEST._serialized_start=134
  _GETXTZBAKERREQUEST._serialized_end=188
  _GETXTZBAKERREPLY._serialized_start=190
  _GETXTZBAKERREPLY._serialized_end=248
  _XTZBAKERSERVICE._serialized_start=251
  _XTZBAKERSERVICE._serialized_end=487
# @@protoc_insertion_point(module_scope)
