# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xtzbaker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0extzbaker.proto\x12\x0ctgvalidatord\"\x9d\x03\n\x08XTZBaker\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x13\n\x0bstakingBond\x18\x02 \x01(\t\x12\x16\n\x0estakingBalance\x18\x03 \x01(\t\x12\x17\n\x0fstakingCapacity\x18\x04 \x01(\t\x12\x19\n\x11\x61vailableCapacity\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12\x18\n\x10isStakingAllowed\x18\x07 \x01(\x08\x12\x13\n\x0btotalStaked\x18\x08 \x01(\t\x12\x16\n\x0e\x65xternalStaked\x18\t \x01(\t\x12\x12\n\noverStaked\x18\n \x01(\t\x12\x1f\n\x17\x65xternalStakingCapacity\x18\x0b \x01(\t\x12\x16\n\x0etotalDelegated\x18\x0c \x01(\t\x12\x19\n\x11\x65xternalDelegated\x18\r \x01(\t\x12\x1a\n\x12\x64\x65legationCapacity\x18\x0e \x01(\t\x12#\n\x1b\x61vailableDelegationCapacity\x18\x0f \x01(\t\x12\x1f\n\x17\x65\x64geOfBakingOverStaking\x18\x10 \x01(\tB#\n!com.taurushq.sdk.protect.proto.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xtzbaker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.taurushq.sdk.protect.proto.v1'
  _XTZBAKER._serialized_start=33
  _XTZBAKER._serialized_end=446
# @@protoc_insertion_point(module_scope)
